pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories { google(); mavenCentral(); maven { url = uri("https://storage.googleapis.com/download.flutter.io") } }
}
rootProject.name = "LifeMate"
include(":app")

// Generated by the pinned Flutter SDK before Gradle runs. No second APK/application ID.
apply(from = "life_mate_flutter/.android/include_flutter.groovy")
